### ISSUE TITLE
Netherite Shears not giving the Time for a haircut Advancement

### ISSUE THREAD

**Issue by asdasdasadg** [OroArmorModding/Netherite-Plus-Mod#122]
https://user-images.githubusercontent.com/84078980/120398282-93cee600-c342-11eb-8515-dfcea9e3e3f7.png

version: netherite-plus-mod-1.4.5-1.16.5-forge

**Comment by Hir0shiyt** [comment]
True, i've that problem as well

**Comment by zealoussentinel512** [comment]
You can close this issue now. It's fixed.
