### ISSUE TITLE
[Fabric |- Crash with quilt loader 1.19.1

### ISSUE THREAD

**Issue by kingslayerrrr** [OroArmorModding/Netherite-Plus-Mod#148]
**Describe the bug**
The mod crash the game when i run it, im using Quilt 1.19.1

**To Reproduce**
install netherite plus mod + multi item lib and then run the game with quilt mod loader 1.19.1 and then boom you have the issue that i found

**Expected behavior**

**Screenshots**
![image](https://user-image
![Screenshot (2353)](https://user-images.githubusercontent.com/110042813/185776145-4de78cda-cd3b-475d-b58a-d40fe5772d02.png)
s.githubusercontent.com/110042813/185776138-12cb8e6e-5bdb-4725-b72b-eae3513487ba.png)

**Comment by zealoussentinel512** [comment]
I've got the same problem. It'd be better, if the mod was also on fabric or forge.

**Comment by CyberSteve777** [comment]
The mod won't be on Fabric/Forge unless somebody port it. Also, the mod crashing on startup is known issue
