### ISSUE TITLE
Fabric 1.19.2

### ISSUE THREAD

**Issue by MOOOOs** [OroArmorModding/Netherite-Plus-Mod#149]
*Describe the feature you'd like**
Fabric 1.19.2 update because quilt is not having much mods and will never have because its not well known mod loader

**Describe how this feature adheres to the vanilla feel**
better mod loader

**Additional context**
Examples of other mods having similar features (Not required).

**Comment by OroArmor** [comment]
Bad issue. Fabric mods run on Quilt. Quilt has features I need. Use quilt it's better.
