### ISSUE TITLE
[Fabric] - 1.19.4 Netherite Plus with Quilt 1.19.4 (Crash)

### ISSUE THREAD

**Issue by zealoussentinel512** [OroArmorModding/Netherite-Plus-Mod#150]
**Describe the bug**
I've got a certain crash and I'm using Quilt 1.19.4 loader (version 0.18.8). Tell me please how to solve the problem.  Two screenshots below. 

**To Reproduce**
Just install Netherite Plus with multi item lib and newest quilted fabric api for 1.19.4 version.

**Expected behavior**
I expected it to simply work and no any crashes.

**Screenshots**
https://i.imgur.com/29BFMn4.png
https://i.imgur.com/u2i3KET.png

**Comment by OroArmor** [comment]
Could you please upload a full crash report and log?

**Comment by zealoussentinel512** [comment]
How to do this? It's been a while since I played minecraft and now I don't remember.
