### ISSUE TITLE
Netherite plus mod not working for 1.19.4/1.20.1 [Fabric] - Bug

### ISSUE THREAD

**Issue by zealoussentinel512** [OroArmorModding/Netherite-Plus-Mod#153]
**Describe the bug**
For some reason the netherite plus mod version 2.2.0 can't be detected for both minecraft 1.19.4 and 1.20.1
Not sure if it's some bug or something else. I'm using fabric mod platform.

**To Reproduce**
Simply put netherite plus 2.2.0 in the mods section and check by using mod menu in the game or search for additional netherite items in creative menu.

**Expected behavior**
I expected it to work for 1.20.1 and enjoy playing the game with this mod.

**Screenshots**
https://i.imgur.com/QGpAJHJ.png
https://i.imgur.com/lckeMyE.png

**Comment by OroArmor** [comment]
Netherite plus is not longer on fabric. It is a quilt exclusive mod.
